apiVersion: v1
kind: Service
metadata:
  name: counter
  labels:
    app: counter
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: counter
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: batch
          image: just1689/batch:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 64Mi
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: job
              value: "counter"
            - name: address
              value: ":8080"
            - name: nsqAddr
              value: "nsqd:4150"
      terminationGracePeriodSeconds: 5
