apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: batch
          image: just1689/batch:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 64Mi
          ports:
            - containerPort: 8080
              name: tcp
          env:
            - name: job
              value: "worker"
            - name: address
              value: ":8080"
            - name: nsqAddr
              value: "nsqd:4150"
      terminationGracePeriodSeconds: 5
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: worker
  targetCPUUtilizationPercentage: 60
