---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nsqd-budget
  labels:
    app: nsq
    component: nsqd
spec:
  selector:
    matchLabels:
      app: nsq
      component: nsqd
  minAvailable: 1
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nsqlookupd-budget
  labels:
    app: nsq
    component: nsqlookupd
spec:
  selector:
    matchLabels:
      app: nsq
      component: nsqlookupd
  minAvailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    app: nsq
spec:
  ports:
    - port: 4160
      targetPort: 4160
      name: tcp
    - port: 4161
      targetPort: 4161
      name: http
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: nsq
    component: nsqlookupd
---
apiVersion: v1
kind: Service
metadata:
  name: nsqd
  labels:
    app: nsq
spec:
  ports:
    - port: 4150
      targetPort: 4150
      name: tcp
    - port: 4151
      targetPort: 4151
      name: http
  clusterIP: None
  selector:
    app: nsq
    component: nsqd
---
apiVersion: v1
kind: Service
metadata:
  name: nsqadmin
  labels:
    app: nsq
spec:
  ports:
    - port: 4170
      targetPort: 4170
      name: tcp
    - port: 4171
      targetPort: 4171
      name: http
  selector:
    app: nsq
    component: nsqadmin
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nsqlookupd
spec:
  serviceName: "nsqlookupd"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nsq
        component: nsqlookupd
    spec:
      containers:
        - name: nsqlookupd
          image: nsqio/nsq:v1.1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
          ports:
            - containerPort: 4160
              name: tcp
            - containerPort: 4161
              name: http
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 2
          command:
            - /nsqlookupd
      terminationGracePeriodSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nsq
        component: nsqd
    spec:
      containers:
        - name: nsqd
          image: nsqio/nsq:v1.1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
          ports:
            - containerPort: 4150
              name: tcp
            - containerPort: 4151
              name: http
          command:
            - /nsqd
#            - -data-path
#            - /data
            - -lookupd-tcp-address
            - nsqlookupd:4160
            - -lookupd-tcp-address
            - nsqlookupd:4160
            - -lookupd-tcp-address
            - nsqlookupd:4160
            - -broadcast-address
            - $(HOSTNAME).nsqd
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      terminationGracePeriodSeconds: 5

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsq
        component: nsqadmin
    spec:
      containers:
        - name: nsqadmin
          image: nsqio/nsq:v1.1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
          ports:
            - containerPort: 4170
              name: tcp
            - containerPort: 4171
              name: http
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          command:
            - /nsqadmin
            - -lookupd-http-address
            - nsqlookupd:4161
            - -lookupd-http-address
            - nsqlookupd:4161
            - -lookupd-http-address
            - nsqlookupd:4161
      terminationGracePeriodSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nsq
spec:
  rules:
    - host: nsq.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nsqadmin
              servicePort: 4171